---
hostname: blokk

## COMPOSE-GEN
docker_user: "{{ vault.user }}"
docker_dir: "/home/{{ vault.user }}/docker"
compose_containers:
  ### HCI
  hci-website:
    version: "3.3"
    services:
      bnuuy:
        container_name: bnuuy
        ports:
          - "8020:8000"
        image: crccheck/hello-world
        volumes:
          - ./web:/www
        restart: unless-stopped
  ### SHIORI
  shiori:
    version: "3.3"
    services:
      shiori:
        image: radhifadlillah/shiori
        container_name: shiori
        ports:
          - "8070:8080"
        volumes:
          - "./config:/srv/shiori"
        restart: unless-stopped
  ### CHANGE DETECTION
  changedetection:
    version: "3"
    services:
      changedetection:
        image: ghcr.io/dgtlmoon/changedetection.io
        container_name: changedetection
        environment:
          - BASE_URL=https://change.bnuuy.net
        volumes:
          - ./data:/datastore
        ports:
          - 5003:5000
        restart: unless-stopped
