---
hostname: proxy

## COMPOSE-GEN
docker_user: "{{ vault.user }}"
docker_dir: "/home/{{ vault.user }}/docker"
compose_containers:
  ### CADDY & CLOUDFLARED
  proxy:
    version: "3.9"
    services:
      caddy:
        image: caddy:latest
        container_name: caddy
        restart: unless-stopped
        ports:
          - "80:80"
          - "443:443"
          - "443:443/udp"
        volumes:
          - ./Caddyfile:/etc/caddy/Caddyfile
          - ./data:/data
          - ./config:/config
      cloudflared:
        command: "tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}"
        image: "cloudflare/cloudflared:latest"
        container_name: cloudflared
        restart: unless-stopped
  ### NTFY
  ntfy:
    version: "2.1"
    services:
      ntfy:
        image: binwiederhier/ntfy
        container_name: ntfy
        command:
          - serve
        environment:
          - TZ=Europe/Amsterdam
        volumes:
          - ./cache:/var/cache/ntfy
          - ./data:/etc/ntfy
        ports:
          - 8044:80
        restart: unless-stopped

compose_envs:
  proxy:
    CLOUDFLARED_TOKEN: "{{ vault.cloudflared_token }}"

### CADDY
caddy_config_dir: "{{ docker_dir }}/proxy"
# TODO: add config to redirect missing subdomains
caddy_custom_config: |
  (tls) {
    tls {
      dns cloudflare {{ vault.dns_cloudflare_api_key }}
    }
  }
caddy_rp_hosts:
  # this is needed for caddy to grab the cert for the domain
  - subdomain: bnuuy.net
    extra: respond "jijiji"
  - subdomain: ntfy.bnuuy.net
    host: proxy
    port: 8044
  - subdomain: hci.bnuuy.net
    host: kite
    port: 8020
  - subdomain: house.bnuuy.net
    host: proxy
    port: 8080
  # fallback for bnuuy -> bnn
  # see https://caddyserver.com/docs/caddyfile/patterns#redirect-www-subdomain
  - subdomain: "*.bnuuy.net"
    extra: redir https://{labels.2}.bnn.net{uri}
