---
hostname: pve
infrastructure: true
disks: false

package_list:
  - name: curl
  - name: git
  - name: htop
  - name: sudo
  - name: wget

pip_packages:
  - proxmoxer

mergerfs_mount:
  - path: /mnt/storage

# load disks
data_disks:
  - path: /mnt/disk1
    source: /dev/disk/by-id/ata-ST4000VN008-2DR166_ZGY68HA3-part1
    fs: ext4
    opts: defaults
    content: true

# fstab
fstab_mergerfs:
  - source: "/mnt/disk*"
    mountpoint: "/mnt/storage"
    fs: fuse.mergerfs
    opts: "defaults,nonempty,allow_other,use_ino,cache.files=off,moveonenospc=true,dropcacheonclose=true,minfreespace=100G,fsname=mergerfs"

lxc_main:
  - name: kite
    vmid: 232
    unprivileged: true
    gw: 192.168.50.1
    ip: 192.168.50.232
    disk: "tank-store:120"
    ostemplate: "tank-store:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
    cores: 2
    memory: 4096
    mounts:
      mp0: "/mnt/storage,mp=/mnt/storage,backup=0"
    nesting: 1
    keyctl: 1

  - name: crab
    vmid: 200
    unprivileged: true
    gw: 192.168.50.1
    ip: 192.168.50.55
    disk: "speed:120"
    cores: 2
    memory: 4096
    nesting: 1

# pve_vms:
#   - name: hass
#     vmid: 202
#     gw: 192.168.50.1
#     ip: 192.168.50.88
#     disk: "tank:64"
#     ostemplate: "tank-store:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
#     cores: 4
#     vcpus: 2
#     machine: q35
#     bios: ovmf
#     ostype: other
#     memory: 2048
#     nesting: 1

# lxc_mounts:
# - name: jelly
#   vmid: 250
#   unprivileged: true
#   gw: 192.168.50.1
#   ip: 192.168.50.20
#   bridge: vmbr0
#   disk: "speed:60"
#   cores: 8
#   memory: 5120
#   nesting: 1
#   keyctl: 0
# fsmount: cifs
# - name: win
#   vmid: 223
#   unprivileged: true
#   gw: 192.168.50.1
#   ip: 192.168.50.90
#   bridge: vmbr0
#   disk: "speed:60"
#   cores: 8
#   memory: 5120
#   nesting: 1
#   keyctl: 0

## COMPOSE-GEN
docker_user: "{{ vault.user }}"
docker_dir: "/home/{{ vault.user }}/docker"
compose_containers:
  ### PIHOLE
  pihole:
    services:
      pihole:
        container_name: pihole
        image: pihole/pihole:latest
        ports:
          - "53:53/tcp"
          - "53:53/udp"
          - "67:67/udp"
          - "8020:80/tcp"
        environment:
          TZ: "Europe/Amsterdam"
        volumes:
          - "./etc-pihole:/etc/pihole"
          - "./etc-dnsmasq.d:/etc/dnsmasq.d"
        restart: unless-stopped
  ### CADDY
  caddy:
    services:
      caddy:
        # image: caddy:latest
        build: .
        container_name: caddy
        user: 1000:1000
        restart: unless-stopped
        ports:
          - "80:80"
          - "443:443"
          - "443:443/udp"
        volumes:
          - ./Caddyfile:/etc/caddy/Caddyfile
          - ./data:/data
          - ./config:/config
  jellyfin:
    services:
      jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/Amsterdam
        volumes:
          - ./config:/config
          - /mnt/storage/media:/data
        #    devices:
        #      - /dev/dri:/dev/dri
        ports:
          - 8096:8096
        restart: unless-stopped
  plex:
    services:
      plex:
        image: ghcr.io/linuxserver/plex
        container_name: plex
        #network_mode: host
        environment:
          - PUID=1000
          - PGID=1000
          - VERSION=docker
        volumes:
          - ./config:/config
          - /mnt/storage/media:/media
        ports:
          - 32400:32400
        restart: unless-stopped
  samba-server:
    services:
      samba:
        image: crazymax/samba
        container_name: samba
        network_mode: host
        volumes:
          - "./data:/data"
          - "/mnt/storage/downloads/complete/games:/samba/games:ro"
        environment:
          - "TZ=Europe/Amsterdam"
          - "SAMBA_LOG_LEVEL=0"
        restart: unless-stopped
  jellyseerr:
    services:
      jellyseerr:
        image: fallenbagel/jellyseerr:latest
        container_name: jellyseerr
        environment:
          - LOG_LEVEL=debug
          - TZ=Europe/Amsterdam
        ports:
          - 5055:5055
        volumes:
          - ./config:/app/config
        restart: unless-stopped
  ### TimeMachine
  timemachine:
    services:
      timemachine:
        network_mode: "host"
        environment:
          - ADVERTISED_HOSTNAME=TM
          - CUSTOM_SMB_CONF=false
          - CUSTOM_USER=false
          - DEBUG_LEVEL=1
          - EXTERNAL_CONF=
          - HIDE_SHARES=no
          - MIMIC_MODEL=TimeCapsule8,119
          - TM_USERNAME=timemachine
          - TM_GROUPNAME=timemachine
          - TM_UID=1000
          - TM_GID=1000
          - PASSWORD=timemachine
          - SET_PERMISSIONS=false
          - SHARE_NAME=TimeMachine
          - SMB_INHERIT_PERMISSIONS=no
          - SMB_NFS_ACES=no
          - SMB_METADATA=stream
          - SMB_PORT=445
          - SMB_VFS_OBJECTS=acl_xattr fruit streams_xattr
          - VOLUME_SIZE_LIMIT=0
          - WORKGROUP=WORKGROUP
        restart: unless-stopped
        ports:
          - "137:137/udp"
          - "138:138/udp"
          - "139:139"
        volumes:
          - /mnt/storage/timemachine:/opt/timemachine
          - timemachine-var-lib-samba:/var/lib/samba
          - timemachine-var-cache-samba:/var/cache/samba
          - timemachine-run-samba:/run/samba
        ulimits:
          nofile:
            soft: 65536
            hard: 65536
        container_name: timemachine
        image: mbentley/timemachine:smb
    volumes:
      timemachine-var-lib-samba:
      timemachine-var-cache-samba:
      timemachine-run-samba:
  filebrowser:
    services:
      filebrowser:
        container_name: filebrowser
        volumes:
          - /mnt/storage:/srv/storage
          - ./database.db:/database.db
          - ./filebrowser.json:/.filebrowser.json
        user: 1000:1000
        ports:
          - 8560:80
        image: filebrowser/filebrowser
  syncthing:
    services:
      syncthing:
        image: syncthing/syncthing
        container_name: syncthing
        hostname: pve-sync
        environment:
          - PUID=1000
          - PGID=1000
        volumes:
          - /tank/st-sync:/var/syncthing
        ports:
          - 8384:8384 # Web UI
          - 22000:22000/tcp # TCP file transfers
          - 22000:22000/udp # QUIC file transfers
          - 21027:21027/udp # Receive local discovery broadcasts
        restart: unless-stopped

### PIHOLE
# network_cidr: 192.42.0.0/20
pihole_password: "{{ vault.pihole.password }}"
pihole_config_dir: "{{ docker_dir }}/pihole/etc-pihole"
dnsmasq_config_dir: "{{ docker_dir }}/pihole/etc-dnsmasq.d"
running_as_container: true
dns_overrides:
  - { ip: 192.168.50.171, custom_dns: "int.bnuuy.net" }
  - { ip: 100.78.187.125, custom_dns: "int.bnuuy.net" }

### CADDY
caddy_config_dir: "{{ docker_dir }}/caddy"
caddy_rp_hosts:
  - subdomain: spoti.int.bnuuy.net
    host: kite
    port: 8338
  - subdomain: yt.int.bnuuy.net
    host: kite
    port: 8003
  - subdomain: sabnzbd.int.bnuuy.net
    host: kite
    port: 6755
  - subdomain: bookdl.int.bnuuy.net
    host: kite
    port: 8033
  - subdomain: pic.int.bnuuy.net
    host: kite
    port: 2283
  - subdomain: proxmox.int.bnuuy.net
    host: pve
    port: 8006
    proto: https
    extra: |
      reverse_proxy https://pve:8006 {
        transport http {
          tls_insecure_skip_verify
        }
      }
  - subdomain: paper.int.bnuuy.net
    host: nixvm
    port: 28981
  - subdomain: change.int.bnuuy.net
    host: kite
    port: 5003
  - subdomain: pdf.int.bnuuy.net
    host: htz
    port: 8080
  - subdomain: bazarr.int.bnuuy.net
    host: kite
    port: 6767
  - subdomain: prowlarr.int.bnuuy.net
    host: kite
    port: 9696
  - subdomain: radarr.int.bnuuy.net
    host: kite
    port: 7878
  - subdomain: jelly.int.bnuuy.net
    host: pve
    port: 8096
  - subdomain: request.int.bnuuy.net
    host: pve
    port: 5055
  - subdomain: dsm.int.bnuuy.net
    host: oreonas
    proto: https
    port: 5001
    extra: |
      reverse_proxy https://oreonas:5001 {
        transport http {
          tls_insecure_skip_verify
        }
      }
  - subdomain: shiori.int.bnuuy.net
    host: nixvm
    port: 8070
  - subdomain: sonarrtv.int.bnuuy.net
    host: kite
    port: 8988
  - subdomain: readarr.int.bnuuy.net
    host: kite
    port: 8787
  # - subdomain: ntfy.int.bnuuy.net
  #   host: proxy
  #   port: 8044
  - subdomain: lidarr.int.bnuuy.net
    host: kite
    port: 8686
  - subdomain: calibre.int.bnuuy.net
    host: kite
    port: 8083
  - subdomain: translate.int.bnuuy.net
    host: kite
    port: 5050
  - subdomain: home.int.bnuuy.net
    host: homeassistant
    port: 8123
  - subdomain: hci.int.bnuuy.net
    host: kite
    port: 8020
  - subdomain: qbit.int.bnuuy.net
    host: kite
    port: 8090
  # - subdomain: jelly.int.bnuuy.net
  #   host: pve
  #   port: 8096
  - subdomain: uptime.int.bnuuy.net
    host: htz
    port: 3001
  - subdomain: sonarr.int.bnuuy.net
    host: kite
    port: 8989
  - subdomain: docs.int.bnuuy.net
    host: kite
    port: 8000
  - subdomain: plex.int.bnuuy.net
    host: pve
    port: 32400
  - subdomain: pihole.int.bnuuy.net
    host: pve
    port: 8020
    # path: /admin
  - subdomain: ab.int.bnuuy.net
    host: nixvm
    port: 13378
  - subdomain: rss.int.bnuuy.net
    host: htz
    port: 8036
  - subdomain: file.int.bnuuy.net
    host: pve
    port: 8560
  - subdomain: sync-pve.int.bnuuy.net
    host: pve
    port: 8384
  - subdomain: git.int.bnuuy.net
    host: htz
    port: 3005
