---
- name: install pkgs
  hosts: all,!blokk
  become: true
  remote_user: root
  # gather_facts: false
  vars:
    ansible_ssh_pass: "{{ vault.ansible_become_default_password }}"
  vars_files:
    - "vars/vault.yml"
  roles:
    # - role: ahuffman.resolv
    #   resolv_nameservers:
    #     - "1.1.1.1"
    - role: grog.package
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: install/pip_packages
    - role: user
      new_user: "{{ vault.user }}"
    - role: install/ssh
    - role: artis3n.tailscale
      tailscale_up_skip: yes
# TODO: make a role to install nix packages

### LXCs/VMs/VPS
# - name: set up crab
#   hosts: crab
#   become: true
#   vars_files:
#     - "vars/vault.yml"
#   roles:
#     - role: grog.package
#     - role: geerlingguy.docker
#     - role: user
#       new_user: "{{ vault.user }}"
#     - role: install/ssh
#     - role: crab
#     - role: compose_gen

# - name: set up backup
#   hosts: all
#   become: true
#   vars_files:
#     - "vars/vault.yml"
#   roles:
#     - role: grog.package
#       package_list:
#         - name: borgbackup
#         - name: borgmatic
#     - role: backup/borgbase
#     - role: backup/borg
#       borg_encryption_passphrase: "{{ vault.borg_passphrase }}"
#       borg_backup_dirs:
#         - "/home/{{ vault.user }}"
