# Setup playbook to be run as root.
# It creates a user with sudo privileges, sets a password and adds my ssh keys from github.
# it also updates all the packages and makes sure tailscale is installed & up to date

---

- hosts: oreonas
  # due to a bug in synology, we need to change permissions to gather_facts (see https://github.com/ansible/ansible/issues/75832#issuecomment-1017805387)
  gather_facts: false
  ignore_unreachable: true
  
  vars_files:
    - 'vars/vault.yml'
  
  tasks:
    - set_fact:
        ansible_become_password: "{{ vault[inventory_hostname].ansible_become_password }}"
    - name: fix /usr/bin/capsh permissions
      become: true
      file:
        path: /usr/bin/capsh
        mode: 0755


- hosts: all
  ignore_unreachable: true
  user: root

  vars_files:
    - 'vars/vault.yml'

  roles:
    - role: user


- hosts: all

  vars_files:
    - 'vars/vault.yml'

  roles:
    - role: set_sudo_password
    - role: artis3n.tailscale
      become: true
      tailscale_up_skip: true


- hosts: proxmox
  user: root
  roles:
    - role: ironicbadger.proxmox_nag_removal


- hosts: docker,!oreonas

  vars_files:
    - 'vars/vault.yml'
  
  roles:
    - role: set_sudo_password
    - role: geerlingguy.docker
      become: true
      docker_install_compose: true
      docker_users: [ "{{ vault.user }}" ]
