# Setup playbook to be run as root.
# It creates a user with sudo privileges, sets a password and adds my ssh keys from github.
# it also updates all the packages and makes sure tailscale is installed & up to date

---

- hosts: oreonas
  # due to a bug in synology, we need to change permissions to gather_facts (see https://github.com/ansible/ansible/issues/75832#issuecomment-1017805387)
  gather_facts: false
  
  vars_files:
    - 'vars/vault.yml'
  
  tasks:
    - set_fact:
        ansible_become_password: "{{ vault[inventory_hostname].ansible_become_password }}"
    - name: fix /usr/bin/capsh permissions
      become: true
      file:
        path: /usr/bin/capsh
        mode: 0755

- hosts: all,!oreonas
  user: root

  vars_files:
    - 'vars/vault.yml'

  tasks:
    - name: create user
      user:
        name: "{{ vault.user }}"
        groups: sudo
        password: "{{ vault[inventory_hostname].ansible_become_password | password_hash('sha512', vault.salt) }}"
        shell: /bin/bash
    
    - name: import keys from github
      authorized_key:
        user: "{{ vault.user }}"
        state: present
        key: https://github.com/MateoPeri.keys
    
    - name: update all packages
      package:
        name: '*'
        update_cache: true
        state: latest

    - name: installs/updates tailscale
      package:
        name: tailscale
        state: latest
