# Setup playbook to be run as root.
# It creates a user with sudo privileges, sets a password and adds my ssh keys from github.
# it also updates all the packages and makes sure tailscale is installed & up to date

---

- hosts: all
  user: root
  vars_files:
    - 'vars/vault.yml'
  tasks:
    - name: create user
      user:
        name: "{{ vault.user }}"
        groups: sudo
        password: "{{ vault[inventory_hostname].ansible_become_password | password_hash('sha512', vault.salt) }}"
        shell: /bin/bash
    - name: import keys from github
      authorized_key:
        user: "{{ vault.user }}"
        state: present
        key: https://github.com/MateoPeri.keys
    - name: update all packages
      package:
        name: '*'
        update_cache: true
        state: latest

    - name: installs/updates tailscale
      package:
        name: tailscale
        state: latest
